### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by danieljsfernandes** [ztizzlegaming/CSGOWinBig-SteamBot#1]
Hello dude,
I'm testing your bot and when i send a trade offer we received a trade notification and logged as: INFO: TradeOffer notification but don't do nothing anymore... The trade isn't accept ... 

How can i fix it?

Best regards.

**Comment by ztizzlegaming** [comment]
Hey, I think I know the problem, I just now added this to the readme

"Be sure to set "BotControlClass" to "SteamBot.DepositTradeOfferUserHandler"."

**Comment by danieljsfernandes** [comment]
Hello dude,
You tell me in private that can be the steam guard...

So i use my entryfile without steam guard and upload bot to WS 2008 (where i have entryfile) and i got this error:

 http://prntscr.com/86hhcr

Best regards.

**Comment by ztizzlegaming** [comment]
Hmm, that's strange, I have never seen that error before, so I can't be of much help. The only thing I could tell you to do would be to go to http://reddit.com/r/steambot and search for that error, and see if anyone has encountered it before, and how they fixed it. Good luck!

**Comment by M60Warrior** [comment]
I've gotten that error a few times it seems to fix itself for me after awhile.

**Comment by ztizzlegaming** [comment]
Turns out danieljsfernandes didn't have the API Key entered for the bot, and that is why it was giving this error.
