### ISSUE TITLE
Bot - "error occurred fetching the depositor's inventory."

### ISSUE THREAD

**Issue by OhhTony** [ztizzlegaming/CSGOWinBig-SteamBot#12]
[Tony 2015-09-21 22:05:58] INFO: Connecting...
[Tony 2015-09-21 22:05:58] SUCCESS: Done Loading Bot!
[Tony 2015-09-21 22:06:02] SUCCESS: User Authenticated!
[Tony 2015-09-21 22:06:03] INFO: Downloading Schema...
[Tony 2015-09-21 22:06:04] SUCCESS: Schema Downloaded!
[Tony 2015-09-21 22:06:04] SUCCESS: Steam Bot Logged In Completely!
[Tony 2015-09-21 22:07:11] INFO: TradeOffer notification
[Tony 2015-09-21 22:07:12] SUCCESS: Offer approved, accepting.
[Tony 2015-09-21 22:07:16] ERROR: Server deposit request failed, declining trade. Error message:
An error occurred fetching the depositor's inventory.

Is there any particularly reason why this is happening? I'm also having problem's with my tradeURL's not saving in my database so maybe that's the cause but I'm just posting here to see if that's not the case.

**Comment by TheAnthonyNL** [comment]
Deposit inventory is steam fault...

**Comment by OhhTony** [comment]
Ok thanks but can you help me with my database problem. Everything seems to work fine but when you enter your trade url it doesnt save and you have to re-enter it over and over?

**Comment by TheAnthonyNL** [comment]
Anyway im trying to fix this with this solution http://stackoverflow.com/a/21504794 since this error occurs on the check-items.php

**Comment by TheAnthonyNL** [comment]
For saving trade url you have to use the deposit button  since that actualy c alls the save option. The change trade url only update the current existing one.

**Comment by OhhTony** [comment]
I'm testing it out and my deposit button doesn't save the URL.

**Comment by TheAnthonyNL** [comment]
K find and add me on steam.

**Comment by OhhTony** [comment]
I've added you on steam. my account is [here](https://steamcommunity.com/id/OhhhTony)

**Comment by TheAnthonyNL** [comment]
Solved the problems for him.

**Comment by TheAnthonyNL** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/issues/18 for reference.

**Comment by Laessen** [comment]
@TheAnthonyNL Are you sure it is Steam's fault? I had this error for a while, and sometimes still get it, and Steam's servers are fine.

**Comment by TheAnthonyNL** [comment]
Yes.
