### ISSUE TITLE
Trades not accepted

### ISSUE THREAD

**Issue by biorisk2** [ztizzlegaming/CSGOWinBig-SteamBot#13]
I launch the bot, authorize the bot with SteamGuard and it doesn't accept incoming offers, there's no error.

This is the bot console:
https://i.gyazo.com/36960e9ebe2897dbbff3b87627cdcd4b.png

This is the bot config:
https://i.gyazo.com/6607725793464002daa26c67990b9f10.png

**Comment by biorisk2** [comment]
https://i.gyazo.com/2bb9b334688043df6fb5ce112ca96bca.png
Logs

**Comment by TheAnthonyNL** [comment]
Well probably you have to wait 7 days due new login.

**Comment by biorisk2** [comment]
Problem solved.
