### ISSUE TITLE
Send offer error

### ISSUE THREAD

**Issue by danieljsfernandes** [ztizzlegaming/CSGOWinBig-SteamBot#2]
Hello again,
When the bot found a winner he tries to send a offer but he returns this error:
http://imgur.com/bPIUlOV

Any idea?

Best regards.

**Comment by linkzy** [comment]
I get the same error, i suspect its cause of the 7 day trade restriction for loggin on a new device.

**Comment by ztizzlegaming** [comment]
Yea basically what linkzy said, just wait for the 7 day trade ban to end, then try again.
