### ISSUE TITLE
an error occured fetching the depositor's inventory

### ISSUE THREAD

**Issue by iLogix** [ztizzlegaming/CSGOWinBig-SteamBot#20]
Hey, i got the message showed in the topic, someone said its steam fault, but well, this happens EVERYTIME i try to put something in the bot, the 7 days of trade are over, still happens, the database is saving everything fine of my account i guess

STEAM_0:1:19114818
76561197998495365
j8s-3w03

this is whats filled in

and this is my acc 

http://steamrep.com/search?q=logixownz

everything looks fine

**Comment by TheAnthonyNL** [comment]
Its cause steam fucks it up will release fix today.

**Comment by iLogix** [comment]
okay thanks, i hope so, i added you on steam, got some questions to you. :)
