### ISSUE TITLE
TradeError

### ISSUE THREAD

**Issue by ImEmil** [ztizzlegaming/CSGOWinBig-SteamBot#21]
Hello.
My tradebot account is now able to trade since 2 days back.
But whenever someone try to deposit some items it throws this error by some reason.

I know there's an issue opened regarding the same error, but there hasn't been any respons for a long time so I hope for some better luck within this issue.

Here's the error: http://pastebin.com/meEuTMhZ

**Comment by TheAnthonyNL** [comment]
Is your bot fully logged in?

**Comment by ImEmil** [comment]
No. I was like fuck this and deleted all files. :(

I assume you also have the same issue.

**Comment by ImEmil** [comment]
No. I was like fuck this and deleted all files. :(

I assume you also have the same issue.

**Comment by Laessen** [comment]
@TheAnthonyNL This is my exact problem

**Comment by ImEmil** [comment]
Closed 25 days ago. If there would be an solution it would've been posted.

You'd better off finding one of those node.js bots instead.
