### ISSUE TITLE
Offer approved, accepting. And nothing happens.

### ISSUE THREAD

**Issue by CandyPoper** [ztizzlegaming/CSGOWinBig-SteamBot#37]
So I configured the bot, got it running and now when I send an offer to the bot is says that the offer was approved but doesn't accept it nor decline it:

![7ad5975152e35e720d88fd723cf50918](https://cloud.githubusercontent.com/assets/12394998/10947082/a64cea84-832e-11e5-8f99-09643db7504b.png)

Here is my log:

[CSGOResort Bot #1 2015-11-04 19:44:24] INFO: Connecting...
[CSGOResort Bot #1 2015-11-04 19:44:24] SUCCESS: Done Loading Bot!
[CSGOResort Bot #1 2015-11-04 19:44:32] ERROR: Login Error: AccountLogonDenied
[CSGOResort Bot #1 2015-11-04 19:44:32] INTERFACE: This account is SteamGuard enabled. Enter the code via the `auth' command.
[CSGOResort Bot #1 2015-11-04 19:44:57] SUCCESS: User Authenticated!
[CSGOResort Bot #1 2015-11-04 19:44:58] SUCCESS: Offer approved, accepting.
[CSGOResort Bot #1 2015-11-04 19:44:58] INFO: Downloading Schema...
[CSGOResort Bot #1 2015-11-04 19:45:00] SUCCESS: Schema Downloaded!
[CSGOResort Bot #1 2015-11-04 19:45:00] SUCCESS: Steam Bot Logged In Completely!
[CSGOResort Bot #1 2015-11-04 19:45:00] INFO: TradeOffer notification
[CSGOResort Bot #1 2015-11-04 19:50:04] INFO: Connecting...
[CSGOResort Bot #1 2015-11-04 19:50:04] SUCCESS: Done Loading Bot!
[CSGOResort Bot #1 2015-11-04 19:50:09] SUCCESS: User Authenticated!
[CSGOResort Bot #1 2015-11-04 19:50:09] INFO: Downloading Schema...
[CSGOResort Bot #1 2015-11-04 19:50:10] SUCCESS: Schema Downloaded!
[CSGOResort Bot #1 2015-11-04 19:50:10] SUCCESS: Steam Bot Logged In Completely!
[CSGOResort Bot #1 2015-11-04 19:53:41] INFO: TradeOffer notification
[CSGOResort Bot #1 2015-11-04 19:53:42] SUCCESS: Offer approved, accepting.

**Comment by Abdokhaled** [comment]
7 days ban

**Comment by CandyPoper** [comment]
But i tired trading with the bot through steam/chrome and i could so dunno
