### ISSUE TITLE
Not accepting offers

### ISSUE THREAD

**Issue by Murzyneczka** [ztizzlegaming/CSGOWinBig-SteamBot#4]
Hello my old post was very bad i have new one. When someone will send trade offer bot don't want to accept it. Console say's only "Trade offer notification" all of this. I tried most options, changing botcontrol, editing bot control, and many staff.

**Comment by bagda391** [comment]
Same here

**Comment by haroko12345** [comment]
I have this error
![err bot](https://cloud.githubusercontent.com/assets/14159353/9712896/297d9d9a-554e-11e5-89de-bc69aa150799.png)

what is wrong?

**Comment by RatexIndex** [comment]
@haroko12345 make more offers or wait 7 days i think thats the guard tradelock ;)

**Comment by ztizzlegaming** [comment]
Yea or it might be that the person trying to deposit has a private or friends-only inventory. You can change that here: http://steamcommunity.com/id/me/edit/settings/

**Comment by RatexIndex** [comment]
No thats not the problem but i cant turn off the bots after 3-4 good 
games thats not normal
i think anythink doesnt work right can you check this ?

And i fix in my files XSS Attacks ;)

Am 09.09.2015 um 00:23 schrieb Jordan Turley:

**Comment by TheAnthonyNL** [comment]
Actually the steamid 32 is not matching woth the steamid 64, im working on this and will report back when i fixed it.

**Comment by TheAnthonyNL** [comment]
The other thing to edit in order to get it working is:

https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L19

Line 19 till 23 replace them with lines posted below.

```php
# Convert Steam ID to Steam64 ID
$idParts = explode(':', $tradeOwnerSteamId32);
$authServer = $idParts[1];
$accountNumber = $idParts[2];

function steamid32ToSteamid64($steamid32) {
    $iServer = "0";
    $iAuthID = "0";
     
    $szTmp = strtok($steamid32, ":");
     
    while(($szTmp = strtok(":")) !== false)
    {
        $szTmp2 = strtok(":");
        if($szTmp2 !== false)
        {
            $iServer = $szTmp;
            $iAuthID = $szTmp2;
        }
    }
    if($iAuthID == "0")
        return "0";
 
    $steamId64 = bcmul($iAuthID, "2");
    $steamId64 = bcadd($steamId64, bcadd("76561197960265728", $iServer)); 
	$part = explode('.',$steamId64);
	return $part[0];
}

//$tradeOwnerSteamId64 = ($accountNumber * 2) + ($authServer + 76561197960265728);
$tradeOwnerSteamId64 = steamid32ToSteamid64($tradeOwnerSteamId32);
```

**Comment by RatexIndex** [comment]
Thanks for the Reply i wake up atm i leave a command after my tests ^^

**Comment by RatexIndex** [comment]
So problem Fixed with TheAnthonyNL Thanks so mutch Mate ;)
https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/issues/3

Close Request

**Comment by TheAnthonyNL** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/issues/18 for future reference.

**Comment by MaeseppTarvo** [comment]
Hello, what does it mean and why I get this error? "The search query was not sent correctly. Please refresh the page and try again.". What I have to change?
