### ISSUE TITLE
Waited 7 days, bot still not accepting offers

### ISSUE THREAD

**Issue by CandyPoper** [ztizzlegaming/CSGOWinBig-SteamBot#42]
Waited 7 days because of the steam guard but still bot doesn't accept the trade offers, same as before https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/issues/37

**Comment by TheAnthonyNL** [comment]
Add me on steam

**Comment by CandyPoper** [comment]
@TheAnthonyNL helped me :)

The password in password.txt didn't match.
