### ISSUE TITLE
Bot help

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig-SteamBot#50]
I got this problem with my bot.
http://pastebin.com/YyThCghE

Can anyone help me?

**Comment by Braandn** [comment]
Same problem

**Comment by TheAnthonyNL** [comment]
Please check all files which requires the passwords.txt and make sure the path is correct.

This  problem gets nearly posted every single day.

**Comment by GreYzZ** [comment]
@TheAnthonyNL 
you already helped me with teamviewer. xD
Someone can close this

**Comment by TheAnthonyNL** [comment]
@GreYzZ  i know but it was meant for @Braandn  :D.
