### ISSUE TITLE
Not sure if Duplicate error as before

### ISSUE THREAD

**Issue by Visfan** [ztizzlegaming/CSGOWinBig-SteamBot#6]
![generic error?](http://puu.sh/kaOXL/ade6382ef7.png)

**Comment by RatexIndex** [comment]
Your Problem is the Path from the Password.txt you need to edit this all informations are in the Bot readme

**Comment by ztizzlegaming** [comment]
Yea it is number 9 of the little setup guide in the readme. Look there and it will tell how to fix this error.
