### ISSUE TITLE
MinDeposit Price

### ISSUE THREAD

**Issue by Xeroner** [ztizzlegaming/CSGOWinBig-SteamBot#60]
Hi there, enybody know how to change minDepositPrice from $1 to something else and how to change max deposit items from 10 to more ?

**Comment by TheAnthonyNL** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/check-items.php#L164 

https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/blob/master/SteamBot/DepositTradeOfferUserHandler.cs#L113

and in future use the search on github (on both projects).

**Comment by Xeroner** [comment]
Antony Please add me on steam :) inned help
