### ISSUE TITLE
Error when Offer approved

### ISSUE THREAD

**Issue by Xeroner** [ztizzlegaming/CSGOWinBig-SteamBot#64]
[CSBOX.PL 2015-11-30 18:25:50] SUCCESS: Offer approved, accepting.
[CSBOX.PL 2015-11-30 18:25:55] ERROR: Steam API error encountered. Trying again. Tries: 1
[CSBOX.PL 2015-11-30 18:25:56] ERROR: Tried total number of tries, giving up.

OR

[CSBOX.PL 2015-11-30 18:20:39] SUCCESS: Offer approved, accepting.
[CSBOX.PL 2015-11-30 18:20:41] ERROR: Server deposit request failed, declining trade. Error message:
An error occured while fetching market price for an item.

Amy ideas ?

**Comment by linkzy** [comment]
Once my site got arround 5 users playing at the same time i got the same problem.

Steam is blocking your site from getting the prices. Wait a few hours for the unblock then add this:

$stmt = $db->prepare("UPDATE items SET currentPrice='$price' where marketName = '$marketName'");
$stmt->execute();

after this:

if (isset($medianPrice)) {
			$price = doubleval(substr($medianPrice, 1)) * 100;
		} else {
			$price = doubleval(substr($lowestPrice, 1)) * 100;
		}

on check-itens.php

**Comment by Xeroner** [comment]
Yes, i was searching on google, and steam block my page, how long i need to wait for unblock?

**Comment by Xeroner** [comment]
@linkzy are you there?

**Comment by linkzy** [comment]
Some times i got blocked for 30 minutes, some times a couple hours. I just want to point out that the solution that i provided is from another user, but im not finding the orginal post, if someone has the link please post so we can give him the credit.

Also, this solution causes another problem, after a few days your prices are going to be outdated... if i get my site working after this december 9 update im going to make a page for a cronjob to update the prices on a regular basis.

**Comment by Xeroner** [comment]
Will you update your cronjob ?

**Comment by Xeroner** [comment]
@linkzy how your searching about this link ?

**Comment by linkzy** [comment]
I dont have a cronjob yet, i need to make it, but i think its not that hard...

If by searching about this link you mean the page where you change the code... its in the check-itens.php, inside the PHP folder on your site.

**Comment by Xeroner** [comment]
@linkzy  No i mean  ,, solution that i provided is from another user, but im not finding the orginal post, if someone has the link please post so we can give him the credit. ,,

**Comment by linkzy** [comment]
here, i found it... its a litte different, but the idea is the same:

https://github.com/ztizzlegaming/CSGOWinBig/issues/76#issuecomment-158503989

**Comment by Xeroner** [comment]
@linkzy ahh, i was thinking you have idea how to take item prices from some other site then steamcommunity
