### ISSUE TITLE
Error when pot is done

### ISSUE THREAD

**Issue by rfalkner** [ztizzlegaming/CSGOWinBig-SteamBot#65]
Hello 

I have an error when pot limit is reached (i believe thats the mistake).

The error is following: 

![error2](https://cloud.githubusercontent.com/assets/11408524/11485723/2f460588-97b5-11e5-95ad-72cf254a32f4.png)

I'm sorry its written in danish, but basically it says: 
"Error system.nullreferenceexception object reference not set to an instance of an object"

I have no clue why this is happening. 

I have set my $maxPotCount = 2; 

Please let me know if you have any questrions. 

Best regards

**Comment by Xeroner** [comment]
Did you have the newest files from CSGOWINBIG site?

**Comment by Xeroner** [comment]
i was having this same problem and i replaced deposit.php file with original :)

**Comment by rfalkner** [comment]
Only thing i changes is $maxPotCount from 60 to 2, so its easier for me to test. 

I downloaded the source code yesterday, so i guess it's up to date :-)

**Comment by Xeroner** [comment]
Try set PotCount to 999 and check

**Comment by rfalkner** [comment]
It's when drawing a winner im getting the issue. Not when people are depositing skins :-)

**Comment by rfalkner** [comment]
FIXED

**Comment by Xeroner** [comment]
What was the problem?

**Comment by rfalkner** [comment]
Well i dont really know. Did as u said and replaced the old file with a new one.
