### ISSUE TITLE
ERROR sending tradeoffer to winner

### ISSUE THREAD

**Issue by rfalkner** [ztizzlegaming/CSGOWinBig-SteamBot#66]
Basically after drawing a winner the bot says: 

![errorsending](https://cloud.githubusercontent.com/assets/11408524/11509957/79c97818-9861-11e5-882b-cfd2e360326f.png)

OR 

![not sending](https://cloud.githubusercontent.com/assets/11408524/11508982/cfa1930c-985b-11e5-8380-cf867d068bda.png)

The bot is not sending the items to the winnner!

Sorry for the issue spam, but this one i cannot figure out myself. 

Best regards

**Comment by rfalkner** [comment]
@TheAnthonyNL can u help with this issue

**Comment by TheAnthonyNL** [comment]
Errr .... will post this so i look tomorrow

**Comment by rfalkner** [comment]
looking foward

**Comment by MilyGosc** [comment]
Had same problem, but @TheAnthonyNL said that it's imposible and U should ignore errors (only these like in 1st screen) but it's buggy and nowadays U have total random in sending winnings, sometimes it work, sometimes no. I made some tests and generaly it doesn't work when in pot U have more then 15-20 items, under this in 99% times work corectly.

Also can look here - https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/issues/41

**Comment by TheAnthonyNL** [comment]
Yeah im still trying to figure it out...

**Comment by rfalkner** [comment]
I've tried 4-5 pots, all pots with less than 5 items, and non of them have been sent to winner. 
Is there really nothing to do, to fix this issue?

I can't be watching the bot 24/7 really. :-/

**Comment by rfalkner** [comment]
I'm getting Steam API error encountered. Trying again.. Can this not be fixed @TheAnthonyNL ?

**Comment by rfalkner** [comment]
There must be some way to fix this. It's doing it EVERY time

**Comment by TheAnthonyNL** [comment]
Like said i still question mark myself everytime.. for me it does do  i only one time and everything works. For others its like going wild

**Comment by rfalkner** [comment]
Okay i'm an idiot. 

I forgot to change the botInvUrl link in DepositTradeOfferHandler.
